/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BadgeToken__factory } from "./BadgeToken__factory";
export { MyNFT__factory } from "./MyNFT__factory";
